FROM node:20-alpine
RUN corepack enable && corepack prepare pnpm@8.6.9 --activate

WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter web-ui build

ENV PORT=8080
EXPOSE 8080

CMD ["pnpm", "--filter", "web-ui", "start", "--", "-p", "8080"]
