export const strings = {
  siteName: "Faroese Radio",
  siteDescription:
    "A historical record of songs played on Faroese radio stations",
  homeSubtitle:
    "A historical record of every song played on Faroese radio stations.",
  browseAllArtists: "Browse all artists \u2192",
  recentPlays: "Recent plays",
  lastPlayed: "Last played",
  artists: "Artists",
  songs: "Songs",
  plays: "Plays",
  searchArtistsPlaceholder: "Search artists...",
  noArtistsFound: "No artists found",
  noArtistsFoundMatching: (query: string) =>
    `No artists found matching "${query}"`,
  allArtists: "\u2190 All artists",
  play: "play",
  playsLabel: "plays",
  title: "Title",
  station: "Station",
  timePlayed: "Time played",
  previousPage: "\u2190 Previous",
  nextPage: "Next \u2192",
  pageOf: (current: number, total: number) =>
    `Page ${current} of ${total}`,
  notFoundCode: "404",
  notFoundMessage: "This page could not be found.",
  goBackHome: "Go back home",
  navArtists: "Artists",
  navCharts: "Charts",
  navStations: "Stations",
  viewCharts: "View monthly charts \u2192",
  charts: "Charts",
  topArtists: "Top Artists",
  topSongs: "Top Songs",
  noDataForMonth: "No plays recorded for this month.",
  stationsTitle: "Stations",
  totalPlays: "total plays",
  mostRecent: "Most recent",
  topArtistsForStation: "Top artists",
  allStations: "\u2190 All stations",
  footerText: (date: string) => `Tracking Faroese radio since ${date}`,
} as const;
